### ISSUE TITLE
unexpected ConflictError when trying to register a second space using `w3 space register`

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3cli#112]
# Context
* I haven't used w3cli for awhile, so I wanted to test it out again and make sure I can use it to upload things in the future
* ```
   bengo@bengo ~/Pictures/sharkDAO ⚡  w3 --version
   w3, 4.5.0
   ```

# Reproduction Steps

1. create a new space like `w3 space create`.
  * trying to upload after this results in error like `{
    name: 'InsufficientStorage',
    message: 'did:key:z6MkvdiCCfPiXKqBBydr9spaZJ97TrNA8x1SCsXnLFbMjqna has no storage provider'
  }`
2. initiate registration of space to add a storage provider
  ```
  ⚡  w3 space register -e bengo@dag.house
  ```

## Expected Behavior

* The space is registered in such a way that I can then do `w3 up <path-to-file>` to upload a file

## Actual Behavior
* `w3 space register` fails with an error
  ```
  {
    name: 'ConflictError',
    stack: 'ConflictError: Space did:key:z6MkvdiCCfPiXKqBBydr9spaZJ97TrNA8x1SCsXnLFbMjqna cannot be provisioned with bafyreifqtt4u47e2dn26t25ydocsadroza77j2djkwphzvgzbjnos64mq4 and did:web:web3.storage: that subscription is already in use\n' +
      '    at Object.add (/upload-api/tables/consumer.js:153:103)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at Object.put (/upload-api/stores/provisions.js:60:9)\n' +
      '    at add5 (/node_modules/@web3-storage/upload-api/src/provider-add.js:69:10)\n' +
      '    at invoke2 (/node_modules/@ucanto/server/src/server.js:145:23)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at execute (/node_modules/@ucanto/server/src/server.js:104:5)\n' +
      '    at ucanInvocationRouter (/upload-api/functions/ucan-invocation-router.js:204:20)\n' +
      '    at Runtime.handler (/node_modules/src/awslambda.ts:308:1)',
    message: 'Space did:key:z6MkvdiCCfPiXKqBBydr9spaZJ97TrNA8x1SCsXnLFbMjqna cannot be provisioned with bafyreifqtt4u47e2dn26t25ydocsadroza77j2djkwphzvgzbjnos64mq4 and did:web:web3.storage: that subscription is already in use'
  }
  ```
  * the error probably comes from here https://github.com/web3-storage/w3infra/blob/8579f5be71b826845a5a3ce6f273076c7109b823/upload-api/tables/consumer.js#L154
* The space is not registered.
    * i.e. `w3 up GOPR0787.JPG` still fails with error `InsufficientStorage` and `'did:key:z6MkvdiCCfPiXKqBBydr9spaZJ97TrNA8x1SCsXnLFbMjqna has no storage provider'`

```[tasklist]
### Tasks
- [ ] https://github.com/web3-storage/w3infra/pull/246
- [x] re-test after w3infra#246
- [x] wait for w3infra#246 to release to prod w3up
- [x] test w3cli registering two spaces to verify fix in prod
```

**Comment by gobengo** [comment]
I synced with @travis on this and we believe that this WIP PR may make a change that gets rid of the error I'm reporting above, because that PR will allow the `w3 space register` flow to result in second 'provisions' entry corresponding to my same email address / account.

**Comment by gobengo** [comment]
Now that https://github.com/web3-storage/w3infra/pull/246 is merged and released to staging, I'll see if there is a way to test whether what's released to staging fixes the error in this issue

**Comment by gobengo** [comment]
I ran into #113 when trying to test on staging.

@travis tested using a workaround (ie using a fresh `W3_STORE_NAME` with w3cli), and said he was able to use staging to register a second space, which is a good sign that w3infra 246 will resolve this issue once released on prod

**Comment by gobengo** [comment]
I verified that this is no longer reproducible in prod

```
bengo@bengo ~ ⚡  for i in {1..3}; do w3 space create test-$i; w3 space register -e bengo@dag.house; done;
did:key:z6MkrewmRwMCaC8Pm2G2iA4X14MFjBWH5JNGcBGdZgaCCoXG
⁂ space registered to bengo@dag.house
did:key:z6Mkr66sQHvPgzMtF7t6GCFr1nk5mZR9F2xZrvb38pNaUycY
⁂ space registered to bengo@dag.house
did:key:z6MkkD1REXPMsgiexw3zrgF5fC3MFTEYRiYBJHKuaCDPcDWg
⁂ space registered to bengo@dag.house
```
